name: test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'
        bundler-cache: true
    - name: setup
      run: |-
        bundle install -j 4
    - name: script
      run: bundle exec rspec
'on':
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
